# Generated by Django 3.2.3 on 2025-05-30 14:54

from django.db import migrations
import facerecognititon.models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', facerecognititon.models.CustomUserManager()),
            ],
        ),
    ]
