# Generated by Django 5.2.1 on 2025-09-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the recipient', max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number in international format (e.g., +233123456789)', max_length=15)),
                ('department', models.CharField(blank=True, help_text='Department or unit', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Receive alerts')),
                ('priority_level', models.CharField(choices=[('high', 'High Priority - Immediate alerts'), ('medium', 'Medium Priority - Standard alerts'), ('low', 'Low Priority - Summary alerts only')], default='medium', max_length=20)),
                ('alert_for_wanted', models.BooleanField(default=True, help_text='Receive alerts for wanted criminals')),
                ('alert_for_investigation', models.BooleanField(default=True, help_text='Receive alerts for under investigation')),
                ('alert_for_escaped', models.BooleanField(default=True, help_text='Receive alerts for escaped criminals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Recipient',
                'verbose_name_plural': 'Alert Recipients',
            },
        ),
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main SMS Config', max_length=100)),
                ('api_key', models.CharField(help_text='Arkesel API Key', max_length=255)),
                ('sender_id', models.CharField(help_text='Sender ID (max 11 characters)', max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_alerts_enabled', models.BooleanField(default=True, help_text='Enable SMS alerts for criminal detection')),
                ('alert_delay_minutes', models.IntegerField(default=5, help_text='Minutes to wait before sending duplicate alerts')),
                ('include_location', models.BooleanField(default=True, help_text='Include location in SMS alerts')),
                ('include_image_link', models.BooleanField(default=True, help_text='Include image link in SMS alerts')),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'verbose_name_plural': 'SMS Configurations',
            },
        ),
        migrations.AddField(
            model_name='criminal',
            name='face_detected',
            field=models.BooleanField(default=False, help_text='Whether a face was successfully detected in the image'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='face_detection_confidence',
            field=models.FloatField(blank=True, help_text='Confidence of face detection', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='Primary face embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='face_embeddings_backup',
            field=models.JSONField(blank=True, help_text='Additional face embeddings for better accuracy', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='face_quality_score',
            field=models.FloatField(blank=True, help_text='Quality score of the primary face (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='image_processed',
            field=models.BooleanField(default=False, help_text='Whether the image has been processed for face recognition'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='processing_notes',
            field=models.TextField(blank=True, help_text='Notes about face processing'),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='camera_location',
            field=models.CharField(blank=True, help_text='Description of camera location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='detection_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score of the detection', null=True),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='detection_method',
            field=models.CharField(default='realtime_webcam', help_text='Method used for detection', max_length=50),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='sms_alert_sent',
            field=models.BooleanField(default=False, help_text='Whether SMS alert has been sent'),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='sms_recipients',
            field=models.JSONField(blank=True, help_text='List of phone numbers that received alerts', null=True),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='sms_response',
            field=models.JSONField(blank=True, help_text='SMS gateway response', null=True),
        ),
        migrations.AddField(
            model_name='criminallastspotted',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When SMS alert was sent', null=True),
        ),
    ]
