# Generated by Django 5.2.1 on 2025-09-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0003_alertrecipient_smsconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the authorized person', max_length=255)),
                ('id_number', models.CharField(help_text='Student ID or Staff ID', max_length=100, unique=True)),
                ('department', models.CharField(help_text='Department or faculty', max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('lecturer', 'Lecturer'), ('admin', 'Administrator')], default='student', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authorized/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this person is currently authorized')),
                ('face_embedding', models.JSONField(blank=True, help_text='Primary face embedding vector', null=True)),
                ('face_embeddings_backup', models.JSONField(blank=True, help_text='Additional face embeddings for better accuracy', null=True)),
                ('face_quality_score', models.FloatField(blank=True, help_text='Quality score of the primary face (0-1)', null=True)),
                ('face_detected', models.BooleanField(default=False, help_text='Whether a face was successfully detected in the image')),
                ('face_detection_confidence', models.FloatField(blank=True, help_text='Confidence of face detection', null=True)),
                ('image_processed', models.BooleanField(default=False, help_text='Whether the image has been processed for face recognition')),
                ('processing_notes', models.TextField(blank=True, help_text='Notes about face processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnauthorizedDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_name', models.CharField(blank=True, help_text='Name if identified, otherwise Unknown', max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('detection_address', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_captured', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('sms_alert_sent', models.BooleanField(default=False, help_text='Whether SMS alert has been sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, help_text='When SMS alert was sent', null=True)),
                ('sms_recipients', models.JSONField(blank=True, help_text='List of phone numbers that received alerts', null=True)),
                ('sms_response', models.JSONField(blank=True, help_text='SMS gateway response', null=True)),
                ('detection_confidence', models.FloatField(blank=True, help_text='Confidence score of the detection', null=True)),
                ('camera_location', models.CharField(blank=True, help_text='Description of camera location', max_length=255, null=True)),
                ('detection_method', models.CharField(default='realtime_webcam', help_text='Method used for detection', max_length=50)),
                ('access_attempted', models.CharField(default='lecture_hall', help_text='Area where access was attempted', max_length=100)),
                ('handled', models.BooleanField(default=False, help_text='Whether this detection has been handled')),
            ],
        ),
        migrations.RemoveField(
            model_name='criminallastspotted',
            name='criminal',
        ),
        migrations.RemoveField(
            model_name='alertrecipient',
            name='alert_for_escaped',
        ),
        migrations.RemoveField(
            model_name='alertrecipient',
            name='alert_for_investigation',
        ),
        migrations.RemoveField(
            model_name='alertrecipient',
            name='alert_for_wanted',
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='alert_for_unauthorized',
            field=models.BooleanField(default=True, help_text='Receive alerts for unauthorized access attempts'),
        ),
        migrations.AlterField(
            model_name='smsconfiguration',
            name='send_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Enable SMS alerts for unauthorized access detection'),
        ),
        migrations.DeleteModel(
            name='Criminal',
        ),
        migrations.DeleteModel(
            name='CriminalLastSpotted',
        ),
    ]
