# Generated by Django 5.2.1 on 2025-09-16 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0004_authorizedperson_unauthorizeddetection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Camera location name (e.g., 'Main Entrance', 'Lecture Hall A')", max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude', max_digits=9)),
                ('area_name', models.CharField(help_text="Area/building name (e.g., 'Computer Science Building')", max_length=100)),
                ('floor', models.CharField(blank=True, help_text="Floor level (e.g., 'Ground Floor', '2nd Floor')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this camera location is active')),
                ('latitude_min', models.DecimalField(blank=True, decimal_places=6, help_text='Minimum latitude boundary', max_digits=9, null=True)),
                ('latitude_max', models.DecimalField(blank=True, decimal_places=6, help_text='Maximum latitude boundary', max_digits=9, null=True)),
                ('longitude_min', models.DecimalField(blank=True, decimal_places=6, help_text='Minimum longitude boundary', max_digits=9, null=True)),
                ('longitude_max', models.DecimalField(blank=True, decimal_places=6, help_text='Maximum longitude boundary', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Location',
                'verbose_name_plural': 'Camera Locations',
            },
        ),
        migrations.AddField(
            model_name='unauthorizeddetection',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Reference to original detection if this is a duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facerecognititon.unauthorizeddetection'),
        ),
        migrations.AddField(
            model_name='unauthorizeddetection',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='Face embedding for duplicate detection', null=True),
        ),
    ]
